version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install DMD and dub
          command: wget https://dlang.org/install.sh | bash -s dmd
      - run:
          name: Install LDC
          command: apt-get install -y ldc
      - run:
          name: Build
          command: ./build.sh